### ISSUE TITLE
How Can I Make Importable Assembly to Add CesWinFormUI to VS ToolBox?

### ISSUE THREAD

**Issue by CesSolutions** [CesSolutions/Ces.WinForm.UI#2]
سلام دوستان.
مشکلی که درحال حاضر دارم این هستش که خروجی پروژه که یک فایل dll هستش را نمیتونم به ToolBox ویژوال استودیو اضافه کنم و مجبورم این پروژه را به عنوان یک پروژه اضافه به Solution اضافه کنم و بعد از یک مرتبه Compile کردن Solution، تمامی کنترل ها به ToolBox اضافه میشه. آیا این مشکل راه حل داره یا به نسخه دات نت مربوط میشه. نسخه جاری 6 هستش. تشکر

**Comment by ghost1372** [comment]
> سلام دوستان. مشکلی که درحال حاضر دارم این هستش که خروجی پروژه که یک فایل dll هستش را نمیتونم به ToolBox ویژوال استودیو اضافه کنم و مجبورم این پروژه را به عنوان یک پروژه اضافه به Solution اضافه کنم و بعد از یک مرتبه Compile کردن Solution، تمامی کنترل ها به ToolBox اضافه میشه. آیا این مشکل راه حل داره یا به نسخه دات نت مربوط میشه. نسخه جاری 6 هستش. تشکر

سلام تنها راهی که بنظر من میرسه شما باید کتابخانه خودتون رو بصورت ناگت ارائه کنید، به کمک ناگت میتونید این کارو انجام بدید و بعد از نصب ناگت کنترل های مشخص شده ایمپورت میشن
قبلا اینجا انجامش دادم 
https://github.com/ghost1372/HandyControls/blob/develop/build/tools/VisualStudioToolsManifest.xml

**Comment by CesSolutions** [comment]
ممنون از راهنمایی شما. حتما این کار را انجام میدم و نتیجه را منعکس میکنم.

**Comment by CesSolutions** [comment]
سلام آقای حسینی. ممنون از راهنمایی شما. با روشی که گفتید مشکل حل شد.

https://www.nuget.org/packages/Ces.WinForm.UI/
